name: belajar_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
